version: '3.8'

services:
  postgres:
    build:
      context: ./db
    container_name: my_postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/user/mydata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    restart: always

  keycloak:
    build:
      context: ./idp
    container_name: my_keycloak
    ports:
      - "8443:8443"
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: localhost
    depends_on:
      - postgres
    restart: always

networks:
  default:
    name: my_network
    driver: bridge
